# Generated by Django 6.0.5 on 2026-05-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_number', models.CharField(max_length=50, verbose_name='Visa Number')),
                ('passport_number', models.CharField(max_length=50, verbose_name='Passport Number')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('fathers_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Father's Name")),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('citizenship', models.CharField(max_length=100, verbose_name='Citizenship')),
                ('passport_issue_date', models.DateField(verbose_name='Passport Issue Date')),
                ('passport_expiry_date', models.DateField(verbose_name='Passport Expiry Date')),
                ('visa_status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('pending', 'Pending')], default='valid', max_length=10, verbose_name='Visa Status')),
                ('visa_valid_from', models.DateField(verbose_name='Visa Valid From')),
                ('visa_validity', models.CharField(choices=[('15_days', '15 Days'), ('30_days', '30 Days'), ('90_days', '90 Days'), ('180_days', '180 Days'), ('1_year', '1 Year')], max_length=20, verbose_name='Visa Validity')),
                ('number_of_entries', models.CharField(choices=[('single_entry', 'Single Entry'), ('double_entry', 'Double Entry'), ('multiple_entry', 'Multiple Entry')], max_length=20, verbose_name='Number of Entries')),
                ('duration_of_stay', models.IntegerField(default=30, verbose_name='Duration of Stay (days)')),
                ('visa_type', models.CharField(choices=[('A', 'Type A'), ('B', 'Type B'), ('C', 'Type C'), ('D', 'Type D')], max_length=2, verbose_name='Visa Type')),
                ('visit_purpose', models.CharField(max_length=255, verbose_name='Visit Purpose')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('approval_date', models.DateField(verbose_name='Approval Date')),
                ('invitation_letter_text', models.TextField(verbose_name='Invitation Letter Text')),
                ('photo_upload', models.ImageField(upload_to='visa_photos/', verbose_name='Photo Upload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Visa',
                'verbose_name_plural': 'Visas',
                'ordering': ['-created_at'],
            },
        ),
    ]
