# Generated by Django 6.0.5 on 2026-05-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='visa',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='invitation_letter_text',
            field=models.TextField(verbose_name='Remarks / Invitation Details'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='passport_number',
            field=models.CharField(max_length=64, verbose_name='Passport Number'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='reference_number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='surname',
            field=models.CharField(max_length=128, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='visa_number',
            field=models.CharField(max_length=64, verbose_name='Visa Number'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='visit_purpose',
            field=models.CharField(choices=[('tourism', 'Tourism'), ('business', 'Business'), ('study', 'Study'), ('medical', 'Medical'), ('other', 'Other')], max_length=20, verbose_name='Visit Purpose'),
        ),
    ]
