# Generated by Django 6.0.5 on 2026-05-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0002_alter_visa_fathers_name_alter_visa_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='visa_pdfs/', verbose_name='PDF Document'),
        ),
    ]
