# Generated by Django 4.2 on 2026-05-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0003_visa_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='visa_validity',
            field=models.DateField(blank=False, null=False, verbose_name='Visa Validity'),
        ),
    ]
